### PR TITLE
0004 - POLMANAGEMENT2

### PR DESCRIPTION
**Pull request by meeth90**
POL Management 

[Rendered](https://github.com/OptimFinance/odao-proposals/blob/07b2a67bf9b5915f5ee41494b81bdaee8f2bfab9/0004%20-%20POLMANAGEMENT2/0004%20-%20POLMANAGEMENT2.md)

### CODE REVIEW

**Comment by Marco112358** [comment]
I'm fully in support of all parts of this proposal

**Comment by Impala111** [comment]
I support the proposal.

**Comment by Asafy77** [comment]
Agree 👍🏼

**Comment by EXG13** [comment]
Its a yes from me

**Comment by Asafy77** [comment]
Its a yes from me


בתאריך יום א׳, 17 בדצמ׳ 2023 ב-10:15 מאת EXG13 ***@***.***>:

**Pull request merged**
